import React from "react";
import Head from "next/head";
import { Inter } from "next/font/google";

import HomeComponent from "./HomeComponent";

const inter = Inter({ subsets: ["latin"] });

export default function Home(): JSX.Element {
  return (
    <React.Fragment>
      <Head>
        <title>SSR Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Next SSR App</h1>
        <HomeComponent data={"test data"} />
      </main>
    </React.Fragment>
  );
}
